### PR TITLE
Update Product.cs

### PR DESCRIPTION
**Pull request by mcakar1993**
This is karthik update the product file

### CODE REVIEW

**Comment by mcakar1993** [comment]
ok i have this doubt

**Review by rakesh2k1032 — COMMENTED** [review]
namespace means where is your classes and interfaces available (Basically which directory)

**Comment by rakesh2k1032** [comment]
got it ?

**Comment by mcakar1993** [comment]
No.. System why in all project

**Comment by rakesh2k1032** [comment]
System is a namespace where all supported classes and interfaces available so always if u create any class the this system namespace will come automatically no need to add.OKKKKKKKK

**Pull request merged**
